### ISSUE TITLE
Clicking "view devices" takes me to chrome://inspect/

### ISSUE THREAD

**Issue by newz2000** [googlearchive/ADBPlugin#2] opened 2013-05-21 15:33 UTC
Hello, after your presentation at i/o last week I wanted to try this out. I've tested in latest Chrome and Canary both and after I click the icon to start ADB then click again to view devices I don't actually get devices, instead it takes me to chrome://inspect/ and from there I'm not sure how to proceed.

I'd love to use this and am happy to help troubleshoot if I can. I'm on Mac OS 10.7 and adb and ddms both work as I'd expect them to when you used from the command line.

**Comment by paulirish** [comment] 2013-05-22 00:34
That's expected behavior. 
If you're not seeing a '1' badge on the android icon then your device isn't yet found. maybe usb debugging isnt turned on for him yet.
Only in canary will you see devices in the inspect page.

**Comment by newz2000** [comment] 2013-05-22 21:52
Hi, thanks, I got it working. However I don't see the "port forwarding" option in my dev tools when I'm inspecting on the mobile device. Is there an option or an update I need to get that feature?

**Comment by grayghostvisuals** [comment] 2013-06-02 17:47
**Setup** 
- MacBook Air OS X version 10.8.3 _running Chrome 27.0.1453.93 stable_
- Samsung Galaxy S4 _running Android 4.2.2 - connected to MacBook Air via USB_
- Chrome for Android w/USB debugging enabled. _Settings > Developer Tools > Enable USB Web debugging_

So I seem to be having the same situation as mentioned above (noting that chrome canary only shows the device from `chrome://inspect`). I've tried w/the CLI before I attempted with this extension. I also dont have anything at `localhost:92222`

**SDK Attempt**
I have the SDK installed in the following directory…
`~/emulators/adt-bundle-mac-x86_64-20130522/`

I use the @paulirish dotfile bonanza so I have the following `PATH` in my `.extra` file that resides at `~/.extra`
`PATH=$PATH:~/emulators/adt-bundle-mac-x86_64-20130522/sdk/platform-tools/`

If I run `adb devices` from the platform-tools dir of the sdk I still don't have my S4 reported as attached. Although if I run an emulator the emulator will show up as a device attached :\ I've attempted restarting the smartphone and laptop with the same results for both the CLI and browser extension approach.

**Comment by sfate** [comment] 2013-06-04 09:47
Solved by #7.

**Comment by grayghostvisuals** [comment] 2013-06-04 12:28
@Sfate
I don't see it merged yet, but hopefully this will solve my problem. I'll let you know after I test with this new update.

**Comment by brianleroux** [comment] 2013-06-19 09:14
:+1: seeing the same issue. Chrome Canary / Galaxy S4 (w/ dev mode turned on). There's a little `1` icon buddy but it just redirects to `about:inspect`. :panda_face:

**Comment by kyledetella** [comment] 2013-06-19 14:06
+1 Same issue here. Chrome Canary `29.0.1542.0 canary` and Nexus 4. I get the `1` icon, but no device showing up.

EDIT: After unplugging and plugging the phone back into USB, it shows up. Likely because I enabled Developer Mode on the phone while I was plugged in.

**Comment by sfate** [comment] 2013-06-19 17:07
@brianleroux, @kyledetella 
Because in original extension button "View devices" just has a link that directs you to `about:inspect`.

You can try it with changes from my pull request #7.
There was added port forward option. And after actually port forward the button "View devices" locates you to `localhost:FORWARED_PORT`. Where you can see opened pages on your device that could be inspected.

**Comment by paulirish** [comment] 2013-06-28 23:27
I believe the issues from this ticket are resolved with enabling USB debugging for the phone and remote debugging within Chrome for Android.

After those, as long as you have Chrome open, you should be seeing it within about:inspect as the readme screenshot indicates. Holler if I can make this clearer in the documentation.

**Comment by paulirish** [comment] 2013-06-28 23:28
Improved install docs here https://github.com/GoogleChrome/ADBPlugin#readme

**Closed as completed by paulirish** 2013-06-28 23:27 UTC

**Comment by brianleroux** [comment] 2013-06-29 00:12
:beers: thx @paulirish

**Comment by grayghostvisuals** [comment] 2013-06-29 02:10
@paulirish Thanks as well :punch: :man:
So my problem was developer mode was not enabled on my Galaxy S4. I had to tap the build number 6 times in order to enable USB debugging with dev mode.
